edition = "2021"

blank_lines_upper_bound = 1
force_multiline_blocks = true
group_imports="StdExternalCrate"
imports_granularity = "Module"
imports_layout = "HorizontalVertical"
match_arm_leading_pipes = "Preserve"
max_width = 100
reorder_impl_items = true
reorder_imports = true
reorder_modules = true
tab_spaces = 4
use_field_init_shorthand = true
use_small_heuristics = "Max"
use_try_shorthand = true
